log:
  level: INFO

entryPoints:
  web:
    address: ':80'

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    network: acquisitions-proxy
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: true # Protect with auth or disable before exposing publicly.
